import React, { createContext, useState, useEffect, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        // Check localStorage for saved language preference
        const savedLanguage = localStorage.getItem('language');
        return savedLanguage || 'EN'; // Default to 'EN' if not found
    });

    useEffect(() => {
        // Save language to localStorage whenever it changes
        localStorage.setItem('language', language);
    }, [language]);

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'EN' ? 'SI' : 'EN');
    };

    const translations = {
        EN: {
            home: "HOME",
            about: "ABOUT US",
            contact: "CONTACT",
            login: "LOGIN",
            becomeSeller: "Become a Seller",
            search: "Search...",
            signIn: "Sign in",
            signInAccount: "Sign in to your account",
            or: "Or",
            createAccount: "create a new account",
            username: "Username",
            password: "Password",
            rememberMe: "Remember me",
            forgotPassword: "Forgot your password?",
            createYourAccount: "Create your account",
            alreadyHaveAccount: "Already have an account?",
            fullName: "Full Name",
            address: "Address",
            telephone: "Telephone Number",
            email: "Email Address",
            roleQuestion: "I want to be a:",
            buyer: "Buyer",
            seller: "Seller",
            confirmPassword: "Confirm Password",
            signUp: "Sign up",
            nicNumber: "NIC Number",
            shopName: "Shop Name",
            shopLogo: "Shop Logo",
            aboutTitle: "XCHANGE",
            aboutSubtitle: "Sri Lanka's Premier Multi-Vendor Marketplace",
            ourMission: "Our Mission",
            missionText: "To simplify and revolutionize the online shopping experience in Sri Lanka by providing a secure, transparent, and user-friendly platform that connects buyers with trusted sellers across the island.",
            whyChooseUs: "Why Choose Us?",
            feature1Title: "Verified Sellers",
            feature1Desc: "We ensure all our sellers are verified to provide you with a safe and reliable shopping experience.",
            feature2Title: "Endless Variety",
            feature2Desc: "From electronics and fashion to vehicles and property, find everything you need in one place.",
            feature3Title: "Seamless Communication",
            feature3Desc: "Connect directly with sellers, negotiate prices, and make deals with just a few clicks.",
            joinUs: "Join the Revolution",
            callToAction: "Start your journey with XCHANGE today!",
            contactTitle: "Get in Touch",
            contactSubtitle: "We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
            sendMessage: "Send Message",
            yourName: "Your Name",
            yourEmail: "Your Email",
            yourMessage: "Your Message",
            contactInfo: "Contact Information",
            emailUs: "Email Us",
            callUs: "Call Us",
            visitUs: "Visit Us",
            followUs: "Follow Us",
            quickReply: "Quick Reply",
            chatOnWhatsapp: "Chat on WhatsApp",
            footerDesc: "Sri Lanka's premier multi-vendor marketplace connecting buyers and sellers.",
            company: "Company",
            helpSupport: "Help & Support",
            legal: "Legal",
            newsletter: "Newsletter",
            subscribeText: "Subscribe to our newsletter for the latest updates.",
            enterEmail: "Enter your email",
            subscribe: "Subscribe",
            storeLocations: "Our Stores",
            viewOnMap: "View on Map",
            visitOurShops: "Visit our main outlets across the country.",
            termsConditions: "Terms & Conditions",
            privacyPolicy: "Privacy Policy",
            cookiePolicy: "Cookie Policy",
            faq: "FAQ",
            careers: "Careers",
            blog: "Blog",
            // Become Seller Page
            becomeSellerTitle: "Become a Seller on",
            becomeSellerSubtitle: "Join thousands of successful sellers. Create your shop, list products, and start selling today!",
            shopNameLabel: "Shop Name",
            shopNamePlaceholder: "e.g. Dasun's Gadgets",
            shopLogoLabel: "Shop Logo",
            uploadFile: "Upload a file",
            dragDrop: "or drag and drop",
            fileSizeLimit: "PNG, JPG, GIF up to 5MB",
            fileSelected: "Selected:",
            shopCategoriesLabel: "Shop Categories",
            selectCategoriesPlaceholder: "Select categories...",
            districtLabel: "District",
            selectDistrict: "Select District",
            cityLabel: "City",
            selectCity: "Select City",
            paymentMethodsLabel: "Accepted Payment Methods",
            cod: "Cash on Delivery",
            onlineTransfer: "Online Transfer",
            cardPayment: "Card Payment",
            registerShopButton: "Register Shop"
        },
        SI: {
            home: "මුල් පිටුව",
            about: "අප ගැන",
            contact: "සම්බන්ධ වන්න",
            login: "ඇතුල් වන්න",
            becomeSeller: "විකුණුම්කරුවෙකු වන්න",
            search: "සොයන්න...",
            signIn: "ඇතුල් වන්න",
            signInAccount: "ඔබගේ ගිණුමට ඇතුල් වන්න",
            or: "හෝ",
            createAccount: "නව ගිණුමක් සාදන්න",
            username: "පරිශීලක නාමය",
            password: "මුරපදය",
            rememberMe: "මාව මතක තබාගන්න",
            forgotPassword: "මුරපදය අමතකද?",
            createYourAccount: "ඔබගේ ගිණුම සාදන්න",
            alreadyHaveAccount: "දැනටමත් ගිණුමක් තිබේද?",
            fullName: "සම්පූර්ණ නම",
            address: "ලිපිනය",
            telephone: "දුරකථන අංකය",
            email: "විද්‍යුත් තැපෑල",
            roleQuestion: "මට සිදුවීමට අවශ්‍ය වන්නේ:",
            buyer: "ගැනුම්කරු",
            seller: "විකුණුම්කරු",
            confirmPassword: "මුරපදය තහවුරු කරන්න",
            signUp: "ලියාපදිංචි වන්න",
            nicNumber: "ජාතික හැඳුනුම්පත් අංකය",
            shopName: "වෙළඳසැලේ නම",
            shopLogo: "වෙළඳසැලේ ලාංඡනය",
            aboutTitle: "XCHANGE ගැන",
            aboutSubtitle: "ශ්‍රී ලංකාවේ ප්‍රමුඛතම බහු-වෙළඳ වේදිකාව",
            ourMission: "අපගේ අරමුණ",
            missionText: "දිවයින පුරා සිටින ගැනුම්කරුවන් සහ විශ්වාසවන්ත විකුණුම්කරුවන් සම්බන්ධ කරමින්, ශ්‍රී ලංකාව තුළ ඔන්ලයින් සාප්පු සවාරි අත්දැකීම සරල සහ විප්ලවීය බවට පත් කිරීම.",
            whyChooseUs: "අපව තෝරා ගන්නේ ඇයි?",
            feature1Title: "තහවුරු කළ විකුණුම්කරුවන්",
            feature1Desc: "ඔබට ආරක්ෂිත සහ විශ්වාසදායක සාප්පු සවාරි අත්දැකීමක් ලබා දීම සඳහා අපි අපගේ සියලුම විකුණුම්කරුවන් තහවුරු කරමු.",
            feature2Title: "අසීමිත විවිධත්වය",
            feature2Desc: "ඉලෙක්ට්‍රොනික උපකරණ සහ විලාසිතා සිට වාහන සහ දේපළ දක්වා, ඔබට අවශ්‍ය සියල්ල එකම තැනකින් සොයා ගන්න.",
            feature3Title: "පහසු සන්නිවේදනය",
            feature3Desc: "විකුණුම්කරුවන් සමඟ ඍජුවම සම්බන්ධ වන්න, මිල ගණන් සාකච්ඡා කරන්න, සහ පහසුවෙන් ගනුදෙනු කරන්න.",
            joinUs: "අප හා එක්වන්න",
            callToAction: "අදම XCHANGE සමඟ ඔබේ ගමන ආරම්භ කරන්න!",
            contactTitle: "අප අමතන්න",
            contactSubtitle: "අපි ඔබෙන් ඇසීමට කැමැත්තෙමු. අපට පණිවිඩයක් එවන්න, අපි හැකි ඉක්මනින් ප්‍රතිචාර දක්වන්නෙමු.",
            sendMessage: "පණිවිඩය යවන්න",
            yourName: "ඔබගේ නම",
            yourEmail: "ඔබගේ විද්‍යුත් තැපෑල",
            yourMessage: "ඔබගේ පණිවිඩය",
            contactInfo: "සම්බන්ධතා තොරතුරු",
            emailUs: "විද්‍යුත් තැපෑල",
            callUs: "දුරකථන අංකය",
            visitUs: "ලිපිනය",
            followUs: "අපව අනුගමනය කරන්න",
            quickReply: "ඉක්මන් ප්‍රතිචාරය",
            chatOnWhatsapp: "WhatsApp හරහා කතා කරන්න",
            footerDesc: "ගැනුම්කරුවන් සහ විකුණුම්කරුවන් සම්බන්ධ කරන ශ්‍රී ලංකාවේ ප්‍රමුඛතම බහු-වෙළඳ වේදිකාව.",
            company: "සමාගම",
            helpSupport: "උදව් සහ සහාය",
            legal: "නීතිමය",
            newsletter: "පුවත් හසුන",
            subscribeText: "නවතම තොරතුරු සඳහා අපගේ පුවත් හසුනට දායක වන්න.",
            enterEmail: "ඔබගේ විද්‍යුත් තැපෑල ඇතුළත් කරන්න",
            subscribe: "දායක වන්න",
            storeLocations: "අපගේ වෙළඳසැල්",
            viewOnMap: "සිතියම බලන්න",
            visitOurShops: "දිවයින පුරා පිහිටි අපගේ ප්‍රධාන වෙළඳසැල් වෙත පැමිණෙන්න.",
            termsConditions: "කොන්දේසි සහ නියමයන්",
            privacyPolicy: "රහස්‍යතා ප්‍රතිපත්තිය",
            cookiePolicy: "කුකී ප්‍රතිපත්තිය",
            faq: "නිතර අසන ප්‍රශ්න",
            careers: "රැකියා අවස්ථා",
            blog: "බ්ලොග්",
            // Become Seller Page
            becomeSellerTitle: "XCHANGE හි විකුණුම්කරුවෙකු වන්න",
            becomeSellerSubtitle: "සාර්ථක විකුණුම්කරුවන් දහස් ගණනක් සමඟ එක්වන්න. ඔබේ වෙළඳසැල සාදන්න, නිෂ්පාදන ලැයිස්තුගත කරන්න, සහ අදම විකිණීම ආරම්භ කරන්න!",
            shopNameLabel: "වෙළඳසැලේ නම",
            shopNamePlaceholder: "උදා: දසුන්ගේ ගැජට්",
            shopLogoLabel: "වෙළඳසැලේ ලාංඡනය",
            uploadFile: "ගොනුවක් උඩුගත කරන්න",
            dragDrop: "හෝ ඇද දමන්න",
            fileSizeLimit: "PNG, JPG, GIF 5MB දක්වා",
            fileSelected: "තෝරාගත්:",
            shopCategoriesLabel: "වෙළඳසැලේ වර්ග",
            selectCategoriesPlaceholder: "වර්ග තෝරන්න...",
            districtLabel: "දිස්ත්‍රික්කය",
            selectDistrict: "දිස්ත්‍රික්කය තෝරන්න",
            cityLabel: "නගරය",
            cityLabel: "නගරය",
            selectCity: "නගරය තෝරන්න",
            paymentMethodsLabel: "පිළිගන්නා මුදල් ගෙවීමේ ක්‍රම",
            cod: "භාණ්ඩ ලැබුණු පසු මුදල් ගෙවීම",
            onlineTransfer: "මාර්ගගත මාරු කිරීම්",
            cardPayment: "කාඩ්පත් ගෙවීම්",
            registerShopButton: "වෙළඳසැල ලියාපදිංචි කරන්න"
        }
    };

    const t = translations[language];

    return (
        <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};
